using MapViewer.MapGen;

namespace MapViewer.Tests.Unit;

/// <summary>
/// SeedResolver のユニットテスト。
/// Validates: Requirements 8.3, 8.4
/// </summary>
public class SeedResolverTests
{
    [Fact]
    public void Resolve_WithSpecifiedSeed_ReturnsSameSeed()
    {
        uint seed = 12345u;
        var (resolvedSeed, _) = SeedResolver.Resolve(seed);
        Assert.Equal(seed, resolvedSeed);
    }

    [Fact]
    public void Resolve_WithSpecifiedSeed_ProducesDeterministicRng()
    {
        uint seed = 42u;
        var (_, rng1) = SeedResolver.Resolve(seed);
        var (_, rng2) = SeedResolver.Resolve(seed);

        // 同じシードから生成された Random は同じ系列を出力する
        for (int i = 0; i < 100; i++)
        {
            Assert.Equal(rng1.Next(), rng2.Next());
        }
    }

    [Fact]
    public void Resolve_WithNullSeed_ReturnsNonNullSeed()
    {
        var (resolvedSeed, rng) = SeedResolver.Resolve(null);

        // シードが自動生成されている
        Assert.NotNull(rng);
        // resolvedSeed は uint なので常に有効な値
        Assert.True(resolvedSeed >= 0);
    }

    [Fact]
    public void Resolve_WithNullSeed_ReturnsWorkingRng()
    {
        var (_, rng) = SeedResolver.Resolve(null);

        // 自動生成シードでもRNGが正常に動作する
        var value = rng.Next();
        Assert.True(value >= 0);
    }

    [Fact]
    public void Resolve_WithSameAutoGeneratedSeed_ProducesSameSequence()
    {
        // 自動生成されたシードを使って再度Resolveすれば同じ系列が得られる
        var (autoSeed, _) = SeedResolver.Resolve(null);
        var (_, rng1) = SeedResolver.Resolve(autoSeed);
        var (_, rng2) = SeedResolver.Resolve(autoSeed);

        for (int i = 0; i < 50; i++)
        {
            Assert.Equal(rng1.Next(), rng2.Next());
        }
    }

    [Theory]
    [InlineData(0u)]
    [InlineData(1u)]
    [InlineData(uint.MaxValue / 2)]
    [InlineData(uint.MaxValue)]
    public void Resolve_WithVariousSeeds_ProducesValidRng(uint seed)
    {
        var (resolvedSeed, rng) = SeedResolver.Resolve(seed);
        Assert.Equal(seed, resolvedSeed);
        // RNG が正常に値を生成できる
        var value = rng.Next();
        Assert.True(value >= 0);
    }
}
